before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
language: node_js
sudo: true
dist: trusty
before_script: npm install -g web-component-tester
env:
  global:
    - secure: gZ5vpMlc9fuKSZeMmT6xf4+FIVWxET6f6Lkp6l5Qo9vL2X/KC/bMJF1v2w5xXFLFTdm/hPUDkeQRDUBBJhGcsXhJeWIvAXdPkObV9ZPRwpDnnN1qU5lOqVIy6gFjDm2Wm6UNXcRnyP1TrGpMwbG13EUtD0rF8LZqBm3B833sKS4=
    - secure: DObDewETPYiIsASeC3UETPbQ6YBniRZdNV2eTM1xULvuFNDxXJD09KKyWOiMduublEIJRXLjBIXmD8cbVsgrbRUYA4bxcXffDeuc6q6HaQGU9HvIbLz6o3/oxi4fX2G9GwrZtijW2p2Rgw2l9koR3ovjcM97CSTWFUMh5rtXag8=
    - CXX=g++-4.8
node_js: stable
cache:
  directories:
    - bower_components
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
sauce_connect: true
script: npx wct --module-resolution=node --npm --plugin sauce --skip-plugin local

