# NOTE: Not using fs-common-build-scripts common imports, because this code is a stupid public fork
version: ~> 1.0

# Branch whitelist
branches:
  only:
    - master
# Caching of bower_components & node_modules disabled, due to an increase in delayed breakages
cache:
  npm: false
  directories: null
dist: trusty
language: node_js
node_js:
  - 10
os: linux

before_install:
  # Create .netrc for access to install private repositories
  # NOTE: Use > (overwrite), not >> (append), because Travis CI helpfully creates one for us.
  - 'echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" > ~/.netrc'

install:
  - npm install -g bower
  - bower install --config.interactive=false
  - npm install

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    # Custom template used because SUCCESS/FAILURE is all the way at the end by default
    template:
      - '%{result}: %{repository} <%{build_url}|#%{build_number}>  (<%{compare_url}|%{commit}>)'
      - "\tin %{duration} for %{author}'s commit:"
      - "\t\"%{commit_subject}\""
    on_pull_requests: false
    on_success: change
    on_failure: change
    rooms:
      - 'familysearch:S4NvL7BI3BFGOMfoiSCfARk5#treeweb-gold-builds'

before_script:
  - bash node_modules/fs-common-build-scripts/bin/before_script.sh
script:
  # Run linting checks, suppressing warnings for cleanliness
  - npm run lint:quiet
  # Run tests
  - npm run test:ci
after_success:
  - node node_modules/fs-common-build-scripts/bin/create_release.js
after_failure:
  - bash node_modules/fs-common-build-scripts/bin/report_failure_details.sh
after_script:
  - bash node_modules/fs-common-build-scripts/bin/after_script.sh
